"""initial tables

Revision ID: 45d68e5fba30
Revises: 
Create Date: 2025-02-17 21:00:01.149819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d68e5fba30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_category', sa.Enum('LANCHE', 'ACOMPANHAMENTO', 'BEBIDA', 'SOBREMESA', name='productcategoryenum', native_enum=False), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addons_id'), 'addons', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'IN_PREPARATION', 'READY', 'FINALIZED', name='orderstatusenum', native_enum=False), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('finished_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('product_category', sa.Enum('LANCHE', 'ACOMPANHAMENTO', 'BEBIDA', 'SOBREMESA', name='productcategoryenum', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('combos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combos_id'), 'combos', ['id'], unique=False)
    op.create_table('combo_addon',
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addons.id'], ),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.id'], ),
    sa.PrimaryKeyConstraint('combo_id', 'addon_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combo_addon')
    op.drop_index(op.f('ix_combos_id'), table_name='combos')
    op.drop_table('combos')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_addons_id'), table_name='addons')
    op.drop_table('addons')
    # ### end Alembic commands ###
